# Form implementation generated from reading ui file '/Users/nguyenthanhcong/QtDesigner/TDLT_PROJECT/SimpleMath/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 342)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("background:rgb(229, 141, 200);\n"
"color:black\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 240, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButtonadd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonadd.setGeometry(QtCore.QRect(80, 170, 81, 51))
        self.pushButtonadd.setObjectName("pushButtonadd")
        self.pushButtonminus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonminus.setGeometry(QtCore.QRect(180, 170, 81, 51))
        self.pushButtonminus.setObjectName("pushButtonminus")
        self.pushButtonmulti = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonmulti.setGeometry(QtCore.QRect(280, 170, 81, 51))
        self.pushButtonmulti.setObjectName("pushButtonmulti")
        self.pushButtondivide = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtondivide.setGeometry(QtCore.QRect(380, 170, 81, 51))
        self.pushButtondivide.setObjectName("pushButtondivide")
        self.lineEditA = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditA.setGeometry(QtCore.QRect(120, 80, 311, 31))
        self.lineEditA.setObjectName("lineEditA")
        self.lineEditB = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditB.setGeometry(QtCore.QRect(120, 120, 311, 31))
        self.lineEditB.setObjectName("lineEditB")
        self.lineEditResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditResult.setGeometry(QtCore.QRect(120, 230, 311, 31))
        self.lineEditResult.setObjectName("lineEditResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Simple Math</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "A coeff:"))
        self.label_3.setText(_translate("MainWindow", "B coeff:"))
        self.label_4.setText(_translate("MainWindow", "Result :"))
        self.pushButtonadd.setText(_translate("MainWindow", "+"))
        self.pushButtonminus.setText(_translate("MainWindow", "-"))
        self.pushButtonmulti.setText(_translate("MainWindow", "x"))
        self.pushButtondivide.setText(_translate("MainWindow", ":"))
